### PR TITLE
Update `prompt_toolkit` from `3.0.34` to `3.0.43`

### LINKED ISSUE #564: ptpython 3.0.25 fails if older version of prompt-toolkit is present: 3.0.34 vs 3.0.43
After upgrading ptpython to 3.0.25 I got an import error. After force upgrading prompt-toolkit to 3.0.43 things started working again.

Most likely this is caused by the requirements for ptpython not setting the minimum version of prompt-toolkit to the version that provides `OneStyleAndTextTuple`.

Error:
```
> ptpython
Traceback (most recent call last):
  File "/Users/stephane/.pyenv/versions/3.12.1/bin/ptpython", line 5, in <module>
    from ptpython.entry_points.run_ptpython import run
  File "/Users/stephane/.pyenv/versions/3.12.1/lib/python3.12/site-packages/ptpython/__init__.py", line 3, in <module>
    from .repl import embed
  File "/Users/stephane/.pyenv/versions/3.12.1/lib/python3.12/site-packages/ptpython/repl.py", line 23, in <module>
    from prompt_toolkit.formatted_text import OneStyleAndTextTuple
ImportError: cannot import name 'OneStyleAndTextTuple' from 'prompt_toolkit.formatted_text' (/Users/stephane/.pyenv/versions/3.12.1/lib/python3.12/site-packages/prompt_toolkit/formatted_text/__init__.py). Did you mean: 'StyleAndTextTuples'?
```

Versions:
ptpython==3.0.25
prompt-toolkit==3.0.41

In setup.py the minimum version is set to:
        # Use prompt_toolkit 3.0.34, because of `OneStyleAndTextTuple` import.
        "prompt_toolkit>=3.0.34,<3.1.0",

I think @jonathanslenders accidentally swapped 3 and 4: 34 vs 43.
https://github.com/prompt-toolkit/ptpython/commit/eda7f58d453c3c1b96e4357dfa203f3160cfc4c1

### PR DESCRIPTION
**Pull request by macserv**
Resolves https://github.com/prompt-toolkit/ptpython/issues/564 where `cannot import name 'OneStyleAndTextTuple'` is emitted when launching `ptipython`.

### CODE REVIEW

**Comment by macserv** [comment]
Closed, wrong merge destination.
